chaos-mesh:
  dashboard:
    create: true
    securityMode: false
  
  bpfki:
    create: true
  
  controllerManager:
    targetNamespace: "manifest-gen"

  chaosDaemon:
    runtime: containerd
    socketPath: /run/containerd/containerd.sock